### ISSUE TITLE
Any chance for RSS?

### ISSUE THREAD

**Issue by bebraw** [christianalfoni/christianalfoni.github.io#1]
Would it be possible for you to generate a RSS or Atom? It would be easier to consume content that way.

**Comment by christianalfoni** [comment]
Hi @bebraw,

Thanks for the input. Could you check out a post now? Should have a RSS feed button :-)

Let me know if the formatting is bad etc.

**Comment by bebraw** [comment]
Looks great through NewsBlur. Thanks!
