### ISSUE TITLE
RSS post links are broken

### ISSUE THREAD

**Issue by bebraw** [christianalfoni/christianalfoni.github.io#2]
I'm getting `http://christianalfoni.github.io/www.christianalfoni.com//javascript/2015/02/22/the-great-angular-component-experiment.html` at NewsBlur. At RSS I can see `www.christianalfoni.com//javascript/2015/02/22/the-great-angular-component-experiment.html`.

You should probably tweak the xml links a bit (add `http://` + eliminate double slash) and commit `CNAME` file with your domain to your repo so that your domain works correctly. Now posts route to `github.io`. You can find more information about that CNAME bit at GitHub Pages documentation. You'll need to do some DNS configuration as well.

**Comment by christianalfoni** [comment]
Will fix all of this on new blog, can not seem to find the time ;-)

Thanks for mentioning it @bebraw!
